// gameInfo
export const SET_GAME_INFO = "SET_GAME_INFO";
export const CREATE_GAME = "CREATE_GAME";
export const ADD_SELECTED_CARD = "ADD_SELECTED_CARD";
export const DELETE_SELECTED_CARD = "DELETE_SELECTED_CARD";
export const TOGGLE_SELECTED_MELD = "TOGGLE_SELECTED_MELD";
export const TOGGLE_MY_TURN = "TOGGLE_MY_TURN";

// uiInfo
export const SET_UI_INFO = "SET_UI_INFO";
